[package]
name = "cargo-new-release"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
dialoguer = "0.7.1"
regex = "1.4.2"
semver = "0.11.0"
time = "0.2.23"
